name: kohlberg
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  http: ^1.2.1  # Puedes mantener esta versión si funciona bien
  provider: ^6.1.2  # Actualiza a la última versión estable
  google_sign_in: ^6.2.1  # Versión actual
  shared_preferences: ^2.2.2  # Versión actual
  carousel_slider: ^5.1.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/perfil.png
    - assets/images/logo.jpg
    - assets/images/google.png
